version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://your-ec2-ip/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
